"""removed table

Revision ID: 056d75487e9f
Revises: 68a540deb18e
Create Date: 2024-10-10 13:18:02.959320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '056d75487e9f'
down_revision = '68a540deb18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrowed_books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowed_books',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('borrowed_date', mysql.DATETIME(), nullable=False),
    sa.Column('return_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='borrowed_books_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name='borrowed_books_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
